sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t sdawes437/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sdawes437/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-748525008915'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
