sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t sdawes437/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sdawes437/docker-react npm run test
